### ISSUE TITLE
flash of duplicated text

### ISSUE THREAD

**Issue by tehpsalmist** [hakash/jotr#4]
You're probably aware of this, but it would be great if I didn't see my entire note get flashed below the cursor while typing. I'm on a Mac, using iTerm2 and zsh, if that helps. Node 10.8.0.

**Comment by hakash** [comment]
@tehpsalmist Did it occur inside the built-in editor, or in the cli using the `-c some note` option?

**Comment by hakash** [comment]
Agreed, `tiny-cli-editor` needs to go. Found `terminal-kit` which might help doing what I want. Was hoping for a little more pluggable solution, but oh well.

**Comment by tehpsalmist** [comment]
I can imagine it's not a trivial problem/solution.

**Comment by hakash** [comment]
As mentioned in Slack, this bugfix is underway, replacing `tiny-cli-editor` with `termit`, of my own creation.
